backend:
  name: github
  repo: EdSmithe/trident-club # replace with your GitHub repo
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  # Banner
  - name: "banner"
    label: "Banner"
    files:
      - file: "content/banner.json"
        label: "Announcement Banner"
        name: "banner"
        fields:
          - { name: "message", label: "Message", widget: "string" }

  # Homepage
  - name: "home"
    label: "Homepage"
    files:
      - file: "content/home.json"
        label: "Home Content"
        name: "home"
        fields:
          - { name: "title", label: "Hero Title", widget: "string" }
          - { name: "intro", label: "Intro Text", widget: "text" }
          - { name: "video", label: "YouTube Video URL", widget: "string" }

  # Announcements (stored in JSON list)
  - name: "announcements"
    label: "Announcements"
    file: "content/announcements.json"
    fields:
      - label: "Items"
        name: "items"
        widget: "list"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "date", label: "Date", widget: "datetime" }
