backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "banner"
    label: "Banner"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/banner.json"
        label: "Announcement Banner"
        name: "banner"
        fields:
          - { label: "Message", name: "message", widget: "string" }

  - name: "home"
    label: "Homepage"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/home.json"
        label: "Homepage Content"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "YouTube Video ID", name: "youtube_id", widget: "string" }

  - name: "announcements"
    label: "Announcements"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/announcements.json"
        label: "Announcements List"
        name: "announcements"
        fields:
          - label: "Announcements"
            name: "items"
            widget: "list"
            fields:
              - { label: "Announcement", name: "text", widget: "string" }

  - name: "challenges"
    label: "Challenges Page"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/challenges.json"
        label: "Challenges Page Content"
        name: "challenges"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - label: "Challenge"
            name: "challenge"
            widget: "object"
            fields:
              - { label: "Challenge Title", name: "title", widget: "string" }
              - label: "Steps"
                name: "steps"
                widget: "list"
                field: { label: "Step", name: "step", widget: "string" }
              - { label: "Button Text", name: "button_text", widget: "string" }
          - label: "Progress"
            name: "progress"
            widget: "object"
            fields:
              - { label: "XP Percent", name: "xp_percent", widget: "number" }
              - { label: "Badge", name: "badge", widget: "string" }


  - name: "community"
    label: "Community Page"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/community.json"
        label: "Community Page Content"
        name: "community"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "intro", widget: "text" }
          - label: "Discord Embed"
            name: "discord"
            widget: "object"
            fields:
              - { label: "Server ID", name: "server_id", widget: "string" }
              - { label: "Theme", name: "theme", widget: "select", options: ["dark", "light"] }
              - { label: "Width", name: "width", widget: "number" }
              - { label: "Height", name: "height", widget: "number" }
          - label: "Member Highlights"
            name: "highlights"
            widget: "list"
            field: { label: "Highlight", name: "highlight", widget: "string" }

  - name: "opportunities"
    label: "Opportunities Page"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/opportunities.json"
        label: "Opportunities Page Content"
        name: "opportunities"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - label: "Opportunities"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: "Video URL", name: "video_url", widget: "string", required: false }
              - { label: "Link Text", name: "link_text", widget: "string", required: false }
              - { label: "Link URL", name: "link_url", widget: "string", required: false }

  - name: "ambassadors"
    label: "Ambassadors Page"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/ambassadors.json"
        label: "Ambassadors Page Content"
        name: "ambassadors"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "text" }
          - label: "Video Links"
            name: "video_links"
            widget: "list"
            field: { label: "Video URL", name: "url", widget: "string" }
          - { label: "Commission Title", name: "commission_title", widget: "string" }
          - { label: "Commission Text", name: "commission_text", widget: "text" }
          - { label: "Commission Image", name: "commission_image", widget: "image", required: false }


  - name: "about"
    label: "About Page"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/about.json"
        label: "About Page Content"
        name: "about"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Our Story Title", name: "our_story_title", widget: "string" }
          - { label: "Our Story Text", name: "our_story_text", widget: "text" }
          - { label: "Disclaimer Title", name: "disclaimer_title", widget: "string" }
          - { label: "Disclaimer Text", name: "disclaimer_text", widget: "text" }
          - { label: "Contact Title", name: "contact_title", widget: "string" }
          - { label: "Contact Text", name: "contact_text", widget: "text" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }

  - name: "contact"
    label: "Contact Page"
    roles: ["Admin", "Editor"]
    files:
      - file: "content/contact.json"
        label: "Contact Page Content"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Phone Label", name: "phone_label", widget: "string" }
          - { label: "Phone Number", name: "phone_number", widget: "string" }
          - { label: "Email Label", name: "email_label", widget: "string" }
          - { label: "Email Address", name: "email_address", widget: "string" }
          - { label: "Location Label", name: "location_label", widget: "string" }
          - { label: "Location Text", name: "location_text", widget: "string" }
          - { label: "Hours Label", name: "hours_label", widget: "string" }
          - { label: "Hours Text", name: "hours_text", widget: "text" }
          - label: "Social Links"
            name: "socials"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string", required: false }
              - { label: "Instagram", name: "instagram", widget: "string", required: false }
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }

